[versions]
agp = "8.5.2"
kotlin = "2.0.20"
compose-bom = "2024.09.00"
core-ktx = "1.13.1"
lifecycle = "2.8.6"
room = "2.6.1"
datastore = "1.1.1"
biometric = "1.2.0-alpha05"
activity-compose = "1.9.2"
coroutines = "1.8.1"
junit = "4.13.2"
robolectric = "4.13"
test-core = "1.6.1"
ksp = "2.0.20-1.0.24"
sshj = "0.38.0"
bcprov = "1.78.1"
slf4j = "2.0.13"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
junit4 = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
test-core = { group = "androidx.test", name = "core", version.ref = "test-core" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
sshj = { group = "com.hierynomus", name = "sshj", version.ref = "sshj" }
bcprov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bcprov" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended" }

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
